---

- name: distribution specific languages
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - fallback.yml
  tags:
    - always

- debug: msg={{ vagrant.pkg_mgr }}
  tags:
    - debug

- name: Vagrant package
  package:
    name: vagrant
    state: present
    use: "{{ vagrant.pkg_mgr|default(ansible_pkg_mgr) }}"
